# Generated by Django 5.2.11 on 2026-07-22 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('max_volunteers', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('allocation_mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('main_student_coordinator', models.ForeignKey(blank=True, help_text='Lead student coordinator for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_events', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('required_volunteers', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty_head', models.ForeignKey(blank=True, help_text='Faculty member in charge of this committee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_committees', to='accounts.userprofile')),
                ('student_coordinator', models.ForeignKey(blank=True, help_text='Student lead for this committee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_committees', to='accounts.userprofile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='events.event')),
            ],
            options={
                'ordering': ['event', 'name'],
            },
        ),
    ]
