# Generated by Django 5.2.11 on 2026-07-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allocation_mode',
            field=models.CharField(choices=[('pool', 'General Pool with Preferences'), ('manual', 'Manual'), ('auto', 'Auto')], default='pool', max_length=10),
        ),
    ]
