# Generated by Django 5.2.11 on 2026-07-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_hours', models.PositiveIntegerField(default=1, help_text='Number of shift periods for this day (1–12)')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('sent_back', 'Sent Back')], default='not_submitted', max_length=20)),
                ('feedback', models.TextField(blank=True, help_text="Dean's feedback when sheet is sent back for corrections")),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sheets', to='events.committee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sheets', to='accounts.userprofile')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_sheets', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Attendance Sheet',
                'verbose_name_plural': 'Attendance Sheets',
                'ordering': ['-date'],
                'unique_together': {('committee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.JSONField(default=list, help_text='List of booleans, one per shift period (e.g. [true, true, false])')),
                ('total_hours', models.PositiveIntegerField(default=0, help_text='Pre-computed count of True values in hours list')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.userprofile')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='volunteers.attendancesheet')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['student__user__first_name'],
                'unique_together': {('sheet', 'student')},
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(blank=True, help_text='Past volunteering experience')),
                ('skills', models.TextField(blank=True, help_text='Relevant skills or certifications')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_committee', models.ForeignKey(blank=True, help_text='Committee the student was assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_volunteers', to='events.committee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.event')),
                ('preference_1', models.ForeignKey(help_text='1st choice committee', on_delete=django.db.models.deletion.CASCADE, related_name='pref1_applications', to='events.committee')),
                ('preference_2', models.ForeignKey(blank=True, help_text='2nd choice committee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref2_applications', to='events.committee')),
                ('preference_3', models.ForeignKey(blank=True, help_text='3rd choice committee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref3_applications', to='events.committee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Volunteer Application',
                'verbose_name_plural': 'Volunteer Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'event')},
            },
        ),
    ]
