# Generated by Django 5.2.11 on 2026-07-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason provided by student if application is cancelled'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
