# Generated by Django 5.2.11 on 2026-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteerapplication_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='cancellation_requested_at',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when registration was cancelled', null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason provided by student for cancelling registration', null=True),
        ),
    ]
