# Generated by Django 5.2.11 on 2026-07-22 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Lowercase email prefix before the 4-digit year+roll (e.g. 'msccs')", max_length=20, unique=True)),
                ('full_name', models.CharField(help_text="Full course name (e.g. 'MSc Computer Science')", max_length=150)),
                ('short_name', models.CharField(help_text="Uppercase short label for batch names (e.g. 'MSCCS')", max_length=20)),
                ('duration_years', models.PositiveIntegerField(help_text='Course duration in years (e.g. 2)')),
                ('department', models.CharField(help_text="Department name (e.g. 'Computer Science')", max_length=100)),
            ],
            options={
                'verbose_name': 'Course Configuration',
                'verbose_name_plural': 'Course Configurations',
                'ordering': ['department', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dean', 'Dean of Student Affairs'), ('faculty', 'Faculty'), ('student', 'Student')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('designation', models.CharField(blank=True, choices=[('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('teaching_associate', 'Teaching Associate')], help_text='Academic designation (faculty only)', max_length=30)),
                ('is_hod', models.BooleanField(default=False, help_text='True if this user is Department Dean/HOD')),
                ('class_batch', models.CharField(blank=True, help_text="Auto-generated batch label (e.g. 'MSCCS - 25-27')", max_length=50)),
                ('department', models.CharField(blank=True, help_text="Department name (e.g. 'Computer Science')", max_length=100)),
                ('admission_year', models.PositiveIntegerField(blank=True, help_text='2-digit admission year extracted from email (e.g. 25)', null=True)),
                ('roll_number', models.CharField(blank=True, help_text="Roll number extracted from email (e.g. '24')", max_length=10)),
                ('is_first_login', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
