# Generated by Django 5.2.11 on 2026-07-26 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_notification_options_notification_count_and_more'),
        ('events', '0003_alter_event_allocation_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.committee'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='Aggregated count for repeated alerts'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
